//+------------------------------------------------------------------+
//| BCA MT4 AUTO EXECUTION EA V1                                     |
//+------------------------------------------------------------------+
#property strict
input double DefaultLotSize=0.01; input int Slippage=10; input int MagicNumber=25001; input int MaxSpreadPoints=50;
input bool AllowBuy=true; input bool AllowSell=true; input bool CloseOpposite=false; input bool OneTradePerSymbol=false;
input bool UseDefaultSLTP=true; input int DefaultSLPoints=300; input int DefaultTPPoints=600;
input bool UseTrailingStop=true; input int TrailStartPoints=300; input int TrailDistancePoints=200;
input bool UseBreakEven=true; input int BreakEvenStartPoints=200; input int BreakEvenLockPoints=20;
input string SignalFileName="bca_signal.txt"; string lastSignal="";
int OnInit(){Print("BCA MT4 EA READY Common\\Files\\",SignalFileName);return(INIT_SUCCEEDED);} 
void OnTick(){ManageOpenTrades(); string signal=ReadSignalFile(); if(signal==""||signal==lastSignal)return; lastSignal=signal; ProcessSignal(signal);} 
string ReadSignalFile(){int h=FileOpen(SignalFileName,FILE_READ|FILE_TXT|FILE_COMMON); if(h==INVALID_HANDLE)return""; string c=""; while(!FileIsEnding(h)) c+=FileReadString(h); FileClose(h); return StringTrimLeft(StringTrimRight(c));}
void ProcessSignal(string signal){string d=GetPart(signal,0,"|"); d=StringUpper(d); double lot=GetValueDouble(signal,"LOT",DefaultLotSize); int sl=(int)GetValueDouble(signal,"SL",DefaultSLPoints); int tp=(int)GetValueDouble(signal,"TP",DefaultTPPoints); if(GetSpreadPoints()>MaxSpreadPoints){Print("Spread too high");return;} if(d=="BUY"){if(!AllowBuy)return; if(OneTradePerSymbol&&HasOpenTrade(OP_BUY))return; if(CloseOpposite)CloseType(OP_SELL); ExecuteBuy(lot,sl,tp);} if(d=="SELL"){if(!AllowSell)return; if(OneTradePerSymbol&&HasOpenTrade(OP_SELL))return; if(CloseOpposite)CloseType(OP_BUY); ExecuteSell(lot,sl,tp);} if(d=="CLOSE")CloseAll(); if(d=="CLOSEBUY")CloseType(OP_BUY); if(d=="CLOSESELL")CloseType(OP_SELL);} 
void ExecuteBuy(double lot,int slp,int tpp){double sl=0,tp=0; if(UseDefaultSLTP||slp>0)sl=NormalizeDouble(Ask-slp*Point,Digits); if(UseDefaultSLTP||tpp>0)tp=NormalizeDouble(Ask+tpp*Point,Digits); int t=OrderSend(Symbol(),OP_BUY,lot,Ask,Slippage,sl,tp,"BCA BUY",MagicNumber,0,clrGreen); if(t<0)Print("BUY failed ",GetLastError()); else Print("BUY ",t);} 
void ExecuteSell(double lot,int slp,int tpp){double sl=0,tp=0; if(UseDefaultSLTP||slp>0)sl=NormalizeDouble(Bid+slp*Point,Digits); if(UseDefaultSLTP||tpp>0)tp=NormalizeDouble(Bid-tpp*Point,Digits); int t=OrderSend(Symbol(),OP_SELL,lot,Bid,Slippage,sl,tp,"BCA SELL",MagicNumber,0,clrRed); if(t<0)Print("SELL failed ",GetLastError()); else Print("SELL ",t);} 
void ManageOpenTrades(){for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue; if(OrderMagicNumber()!=MagicNumber||OrderSymbol()!=Symbol())continue; if(OrderType()==OP_BUY)ManageBuy(); if(OrderType()==OP_SELL)ManageSell();}}
void ManageBuy(){double pp=(Bid-OrderOpenPrice())/Point; double ns=OrderStopLoss(); if(UseBreakEven&&pp>=BreakEvenStartPoints){double be=NormalizeDouble(OrderOpenPrice()+BreakEvenLockPoints*Point,Digits); if(ns<be)ns=be;} if(UseTrailingStop&&pp>=TrailStartPoints){double tr=NormalizeDouble(Bid-TrailDistancePoints*Point,Digits); if(ns<tr)ns=tr;} if(ns>OrderStopLoss()&&ns<Bid) if(!OrderModify(OrderTicket(),OrderOpenPrice(),ns,OrderTakeProfit(),0,clrGreen))Print("Modify buy failed ",GetLastError());}
void ManageSell(){double pp=(OrderOpenPrice()-Ask)/Point; double ns=OrderStopLoss(); if(UseBreakEven&&pp>=BreakEvenStartPoints){double be=NormalizeDouble(OrderOpenPrice()-BreakEvenLockPoints*Point,Digits); if(ns==0||ns>be)ns=be;} if(UseTrailingStop&&pp>=TrailStartPoints){double tr=NormalizeDouble(Ask+TrailDistancePoints*Point,Digits); if(ns==0||ns>tr)ns=tr;} if(ns>Ask&&(OrderStopLoss()==0||ns<OrderStopLoss())) if(!OrderModify(OrderTicket(),OrderOpenPrice(),ns,OrderTakeProfit(),0,clrRed))Print("Modify sell failed ",GetLastError());}
void CloseAll(){CloseType(OP_BUY);CloseType(OP_SELL);} void CloseType(int type){for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue; if(OrderMagicNumber()!=MagicNumber||OrderSymbol()!=Symbol()||OrderType()!=type)continue; bool c=false; if(type==OP_BUY)c=OrderClose(OrderTicket(),OrderLots(),Bid,Slippage,clrGreen); if(type==OP_SELL)c=OrderClose(OrderTicket(),OrderLots(),Ask,Slippage,clrRed); if(!c)Print("Close failed ",GetLastError());}}
bool HasOpenTrade(int type){for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue; if(OrderMagicNumber()==MagicNumber&&OrderSymbol()==Symbol()&&OrderType()==type)return true;} return false;} int GetSpreadPoints(){return(int)((Ask-Bid)/Point);} 
string GetPart(string text,int index,string delimiter){string parts[]; int c=StringSplit(text,StringGetCharacter(delimiter,0),parts); if(index>=0&&index<c)return StringTrimLeft(StringTrimRight(parts[index])); return"";} 
double GetValueDouble(string text,string key,double def){string parts[]; int c=StringSplit(text,'|',parts); key=StringUpper(key); for(int i=0;i<c;i++){string kv[]; int kvc=StringSplit(parts[i],'=',kv); if(kvc==2){string k=StringUpper(StringTrimLeft(StringTrimRight(kv[0]))); string v=StringTrimLeft(StringTrimRight(kv[1])); if(k==key)return StrToDouble(v);}} return def;}
